<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KinshipCalculator.Core\KinshipCalculator.Core.csproj" />
    <ProjectReference Include="..\Utility\MumuyAlgorithm\MumuyAlgorithm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Test-Unit\Data\LongChainsReviewed.json" Link="Data\LongChainsReviewed.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
